In [24]:
# Create a 1D array of numbers from 10 to 50
import numpy as np
arr = np.arange(10, 51)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [23]:
# Create a 3x3 array of random numbers between 0 and 1
import numpy as np
arr = np.random.rand(3, 3)
print(arr)


[[0.54052658 0.78808944 0.497304  ]
 [0.35079189 0.72589949 0.17061251]
 [0.22701411 0.08195618 0.02845268]]


In [19]:
#Find the shape, size, and data type of the array you created in the previous task.
import numpy as np
arr = np.random.rand(3, 3)
shape = arr.shape
size = arr.size
dtype = arr.dtype
print(f"Shape: {shape}")
print(f"Size: {size}")
print(f"Data Type: {dtype}")


Shape: (3, 3)
Size: 9
Data Type: float64


In [17]:
#Add 5 to every element of a 1D array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr += 5
print(arr)


[ 6  7  8  9 10]


In [5]:
#Multiply two 2D arrays element-wise.
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
result = arr1 * arr2
print(result)


[[ 7 16 27]
 [40 55 72]]


In [6]:
"""Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns."""

import numpy as np
arr = np.arange(1, 26).reshape(5, 5)
first_row = arr[0, :]
last_column = arr[:, -1]
subarray = arr[:3, :2]
print("Original Array:\n", arr)
print("\nFirst Row:\n", first_row)
print("\nLast Column:\n", last_column)
print("\nSubarray (First 3 rows, First 2 columns):\n", subarray)


Original Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First Row:
 [1 2 3 4 5]

Last Column:
 [ 5 10 15 20 25]

Subarray (First 3 rows, First 2 columns):
 [[ 1  2]
 [ 6  7]
 [11 12]]


In [7]:
"""Create a 10-element array of random integers between 1 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation."""
import numpy as np
arr = np.random.randint(1, 101, size=10)
max_value = np.max(arr)
min_value = np.min(arr)
mean_value = np.mean(arr)
std_dev = np.std(arr)
print("Array:", arr)
print("Maximum value:", max_value)
print("Minimum value:", min_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Array: [32 85 62 61 37 60 76  3 47 78]
Maximum value: 85
Minimum value: 3
Mean value: 54.1
Standard deviation: 23.649312886424415


In [13]:
#Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
import numpy as np
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
#Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
import numpy as np
matrix_ones = np.ones((3, 3))
arr = np.array([1, 2, 3])
result = matrix_ones + arr
print(result)


[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [15]:
#Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
import numpy as np
arr = np.random.randint(1, 51, size=10)
divisible_by_5 = arr[arr % 5 == 0]
print("Array:", arr)
print("Elements divisible by 5:", divisible_by_5)


Array: [ 7 11 22  1 36 17 13 18  6 34]
Elements divisible by 5: []


In [16]:
#Create two 2x2 matrices and perform matrix multiplication
import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of Matrix Multiplication:\n", result)


Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Result of Matrix Multiplication:
 [[19 22]
 [43 50]]


In [12]:
#Given a 4x4 array, use fancy indexing to extract the diagonal elements.
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
diagonal_elements = arr[np.arange(4), np.arange(4)]
print("Original Array:\n", arr)
print("\nDiagonal Elements:", diagonal_elements)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal Elements: [ 1  6 11 16]
